//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Corrections.Ioms.Bpl.Entities;
namespace Corrections.Ioms.Services.Proxies.Service040410
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://Corrections.Ioms.Bpl/", ConfigurationName = "ISharedAccomAssmnt")]
    public interface ISharedAccomAssmnt
    {
        #region Methods

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddSACRAResultDetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddSACRAResultDetailsResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails AddSACRAResultDetails(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddSACRAResultDetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddSACRAResultDetailsResponse")]
        System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> AddSACRAResultDetailsAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/FetchSACRAResultDetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/FetchSACRAResultDetailsResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> FetchSACRAResultDetails(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultSearchParams searchParams);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/FetchSACRAResultDetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/FetchSACRAResultDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails>> FetchSACRAResultDetailsAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultSearchParams searchParams);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/UpdateSACRAResultDetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/UpdateSACRAResultDetailsResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails UpdateSACRAResultDetails(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/UpdateSACRAResultDetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/UpdateSACRAResultDetailsResponse")]
        System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> UpdateSACRAResultDetailsAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails);

        /* Individual SACRA NTDB Changes #57727 - Starts*/

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddIndividualSACRA", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddIndividualSACRAResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails AddIndividualSACRA(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails individualSacraDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddIndividualSACRA", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/AddIndividualSACRAResponse")]
        System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> AddIndividualSACRAAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails individualSacraDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetIndividualSACRADetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetIndividualSACRADetailsResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> GetIndividualSACRADetails(string offenderId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetIndividualSACRADetails", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetIndividualSACRADetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails>> GetIndividualSACRADetailsAsync(string offenderId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/ValidateIndividualSACRA", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/ValidateIndividualSACRAResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        RecordRowCollection ValidateIndividualSACRA(string offenderId, string sacraTypeCode, string sacraResultCode);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/ValidateIndividualSACRA", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/ValidateIndividualSACRAResponse")]
        System.Threading.Tasks.Task<RecordRowCollection> ValidateIndividualSACRAAsync(string offenderId, string sacraTypeCode, string sacraResultCode);
        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/PrepareSACRAActiveChargeRequests", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/PrepareSACRAActiveChargeRequestsResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        string PrepareSACRAActiveChargeRequests(string cellSharingAssessId, string prisonerIds);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/PrepareSACRAActiveChargeRequests", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/PrepareSACRAActiveChargeRequestsResponse")]
         System.Threading.Tasks.Task<string> PrepareSACRAActiveChargeRequestsAsync(string cellSharingAssessId, string prisonerIds);
        /* Individual SACRA NTDB Changes #57727 - Ends*/
        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/SaveSACRAReportDocument", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/SaveSACRAReportDocumentResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails SaveSACRAReportDocument(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/SaveSACRAReportDocument", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/SaveSACRAReportDocumentResponse")]
        System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> SaveSACRAReportDocumentAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetSACRAReportDocumentInfo", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetSACRAReportDocumentInfoResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails GetSACRAReportDocumentInfo(string cellSharingAssessId);
        [System.ServiceModel.OperationContractAttribute(Action = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetSACRAReportDocumentInfo", ReplyAction = "http://Corrections.Ioms.Bpl/ISharedAccomAssmnt/GetSACRAReportDocumentInfoResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails GetSACRAReportDocumentInfoAsync(string cellSharingAssessId);
        #endregion Methods
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISharedAccomAssmntChannel : ISharedAccomAssmnt, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharedAccomAssmntClient : System.ServiceModel.ClientBase<ISharedAccomAssmnt>, ISharedAccomAssmnt
    {
        #region Constructors

        public SharedAccomAssmntClient()
        {
        }

        public SharedAccomAssmntClient(string endpointConfigurationName)
            : base(endpointConfigurationName)
        {
        }

        public SharedAccomAssmntClient(string endpointConfigurationName, string remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {
        }

        public SharedAccomAssmntClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {
        }

        public SharedAccomAssmntClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {
        }

        #endregion Constructors

        #region Methods

        public Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails AddSACRAResultDetails(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails)
        {
            return base.Channel.AddSACRAResultDetails(resultDetails);
        }

        public System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> AddSACRAResultDetailsAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails)
        {
            return base.Channel.AddSACRAResultDetailsAsync(resultDetails);
        }

        public System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> FetchSACRAResultDetails(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultSearchParams searchParams)
        {
            return base.Channel.FetchSACRAResultDetails(searchParams);
        }

        public System.Threading.Tasks.Task<System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails>> FetchSACRAResultDetailsAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultSearchParams searchParams)
        {
            return base.Channel.FetchSACRAResultDetailsAsync(searchParams);
        }

        public Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails UpdateSACRAResultDetails(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails)
        {
            return base.Channel.UpdateSACRAResultDetails(resultDetails);
        }

        public System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> UpdateSACRAResultDetailsAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails)
        {
            return base.Channel.UpdateSACRAResultDetailsAsync(resultDetails);
        }

        /* Individual SACRA NTDB Changes #57727 - Starts*/

        public Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails AddIndividualSACRA(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails individualSacraDetails)
        {
            return base.Channel.AddSACRAResultDetails(individualSacraDetails);
        }

        public System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> AddIndividualSACRAAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails individualSacraDetails)
        {
            return base.Channel.AddIndividualSACRAAsync(individualSacraDetails);
        }

        public System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> GetIndividualSACRADetails(string offenderId)
        {
            return base.Channel.GetIndividualSACRADetails(offenderId);
        }

        public System.Threading.Tasks.Task<System.Collections.Generic.List<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails>> GetIndividualSACRADetailsAsync(string offenderId)
        {
            return base.Channel.GetIndividualSACRADetailsAsync(offenderId);
        }

        public RecordRowCollection ValidateIndividualSACRA(string offenderId, string sacraTypeCode, string sacraResultCode)
        {
            return base.Channel.ValidateIndividualSACRA(offenderId, sacraTypeCode, sacraResultCode);
        }

        public System.Threading.Tasks.Task<RecordRowCollection> ValidateIndividualSACRAAsync(string offenderId, string sacraTypeCode, string sacraResultCode)
        {
            return base.Channel.ValidateIndividualSACRAAsync(offenderId, sacraTypeCode, sacraResultCode);
        }

        public string PrepareSACRAActiveChargeRequests(string cellSharingAssessId, string prisonerIds)
        {
            return base.Channel.PrepareSACRAActiveChargeRequests(cellSharingAssessId, prisonerIds);
        }

        public System.Threading.Tasks.Task<string> PrepareSACRAActiveChargeRequestsAsync(string cellSharingAssessId, string prisonerIds)
        {
            return base.Channel.PrepareSACRAActiveChargeRequestsAsync(cellSharingAssessId, prisonerIds);
        }

        /* Individual SACRA NTDB Changes #57727 - Ends*/
        public Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails SaveSACRAReportDocument(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails)
        {
            return base.Channel.SaveSACRAReportDocument(resultDetails);
        }

        public System.Threading.Tasks.Task<Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails> SaveSACRAReportDocumentAsync(Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails resultDetails)
        {
            return base.Channel.SaveSACRAReportDocumentAsync(resultDetails);
        }
        
        public Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails GetSACRAReportDocumentInfo(string cellSharingAssessId)
        {
            return base.Channel.GetSACRAReportDocumentInfo(cellSharingAssessId);
        }
        public Corrections.Ioms.Bpl.Movement.SharedAccomAssmnt.Entities.SACRAResultDetails GetSACRAReportDocumentInfoAsync(string cellSharingAssessId)
        {
            return base.Channel.GetSACRAReportDocumentInfoAsync(cellSharingAssessId);
        }


        #endregion Methods
    }
}